In [2]:
import pandas as pd
print(pd.__version__)

3.0.6

In [3]:
city = "Tallinn"
print(city)

Tallinn

In [4]:
data = {
    'customer_id': [1001, 1002, 1003, 1001, 1002, 1004, 1003, 1001, 1005, 1004,
                    1002, 1003, 1005, 1001, 1006, 1004, 1002, 1007, 1003, 1005],
    'sale_date': ['2024-01-15', '2024-01-16', '2024-02-01', '2024-02-20', '2024-03-01',
                  '2024-03-05', '2024-03-15', '2024-04-10', '2024-04-12', '2024-04-20',
                  '2024-05-01', '2024-05-10', '2024-05-15', '2024-06-01', '2024-06-05',
                  '2024-06-10', '2024-06-20', '2024-07-01', '2024-07-05', '2024-07-10'],
    'total_price': [89.99, 45.50, 120.00, 67.30, 55.00, 210.00, 33.50, 145.00, 78.00, 92.00,
                    160.00, 44.00, 88.50, 230.00, 37.00, 175.00, 110.00, 65.00, 95.00, 125.00],
    'store_location': ['Tallinn', 'Tartu', 'Tallinn', 'Tallinn', 'Tartu', 'Pärnu', 'Tallinn', 'Tallinn',
                       'Tartu', 'Pärnu', 'Tartu', 'Tallinn', 'Tartu', 'Tallinn', 'Pärnu', 'Pärnu',
                       'Tartu', 'Tallinn', 'Tallinn', 'Tartu'],
    'product_category': ['Dresses', 'Tops', 'Denim', 'Accessories', 'Tops', 'Denim', 'Tops',
                         'Dresses', 'Denim', 'Accessories', 'Dresses', 'Tops', 'Denim',
                         'Dresses', 'Accessories', 'Denim', 'Tops', 'Accessories', 'Dresses', 'Denim']
}

df = pd.DataFrame(data)
df.head()

   customer_id   sale_date  total_price store_location product_category
0         1001  2024-01-15        89.99        Tallinn          Dresses
1         1002  2024-01-16        45.50          Tartu             Tops
2         1003  2024-02-01       120.00        Tallinn            Denim
3         1001  2024-02-20        67.30        Tallinn      Accessories
4         1002  2024-03-01        55.00          Tartu             Tops

In [5]:
city = "Tallinn"
print(city)

Tallinn

In [6]:
print(df.shape)
df.describe()

(20, 5)

       customer_id  total_price
count     20.00000    20.000000
mean    1003.20000   103.289500
std        1.76516    56.559621
min     1001.00000    33.500000
25%     1002.00000    62.500000
50%     1003.00000    90.995000
75%     1004.25000   130.000000
max     1007.00000   230.000000

In [7]:
revenue = 500
print (revenue)
print (revenue * 2)

500
1000

In [8]:
print(df.shape)
print(df['total_price'].mean())
print(df['total_price'].max())

(20, 5)
103.2895
230.0

In [9]:
prices = [89.99, 45.50, 120.00]
print(prices)
print(sum(prices))
print(len(prices))

[89.99, 45.5, 120.0]
255.49
3

In [10]:
data = {
    'city': ['Tallinn', 'Tartu', 'Pärnu'],
    'revenue': [500, 300, 200]
}
print(data['city'])
print(data['revenue'])

['Tallinn', 'Tartu', 'Pärnu']
[500, 300, 200]

In [11]:
import pandas as pd

data = {
    'city': ['Tallinn', 'Tartu', 'Pärnu'],
    'revenue': [500, 300, 200]
}

df = pd.DataFrame(data)
df

      city  revenue
0  Tallinn      500
1    Tartu      300
2    Pärnu      200

In [12]:
print(df['revenue'].sum())
print(df['revenue'].max())
print(df.shape)

1000
500
(3, 2)

In [13]:
data = {
    'customer_id': [1001, 1002, 1003, 1001, 1002, 1004, 1003, 1001, 1005, 1004,
                    1002, 1003, 1005, 1001, 1006, 1004, 1002, 1007, 1003, 1005],
    'sale_date': ['2024-01-15', '2024-01-16', '2024-02-01', '2024-02-20', '2024-03-01',
                  '2024-03-05', '2024-03-15', '2024-04-10', '2024-04-12', '2024-04-20',
                  '2024-05-01', '2024-05-10', '2024-05-15', '2024-06-01', '2024-06-05',
                  '2024-06-10', '2024-06-20', '2024-07-01', '2024-07-05', '2024-07-10'],
    'total_price': [89.99, 45.50, 120.00, 67.30, 55.00, 210.00, 33.50, 145.00, 78.00, 92.00,
                    160.00, 44.00, 88.50, 230.00, 37.00, 175.00, 110.00, 65.00, 95.00, 125.00],
    'store_location': ['Tallinn', 'Tartu', 'Tallinn', 'Tallinn', 'Tartu', 'Pärnu', 'Tallinn', 'Tallinn',
                       'Tartu', 'Pärnu', 'Tartu', 'Tallinn', 'Tartu', 'Tallinn', 'Pärnu', 'Pärnu',
                       'Tartu', 'Tallinn', 'Tallinn', 'Tartu'],
    'product_category': ['Dresses', 'Tops', 'Denim', 'Accessories', 'Tops', 'Denim', 'Tops',
                         'Dresses', 'Denim', 'Accessories', 'Dresses', 'Tops', 'Denim',
                         'Dresses', 'Accessories', 'Denim', 'Tops', 'Accessories', 'Dresses', 'Denim']
}

df = pd.DataFrame(data)
print(df.shape)
df.head()

(20, 5)

   customer_id   sale_date  total_price store_location product_category
0         1001  2024-01-15        89.99        Tallinn          Dresses
1         1002  2024-01-16        45.50          Tartu             Tops
2         1003  2024-02-01       120.00        Tallinn            Denim
3         1001  2024-02-20        67.30        Tallinn      Accessories
4         1002  2024-03-01        55.00          Tartu             Tops

In [14]:
df.describe()

       customer_id  total_price
count     20.00000    20.000000
mean    1003.20000   103.289500
std        1.76516    56.559621
min     1001.00000    33.500000
25%     1002.00000    62.500000
50%     1003.00000    90.995000
75%     1004.25000   130.000000
max     1007.00000   230.000000

In [15]:
df.dtypes

customer_id           int64
sale_date               str
total_price         float64
store_location          str
product_category        str
dtype: object

In [16]:
print("Unique customers:", df['customer_id'].nunique())
print("Locations:", df['store_location'].unique())
print("Total revenue:", df['total_price'].sum())
df['store_location'].value_counts()

Unique customers: 7
Locations: <StringArray>
['Tallinn', 'Tartu', 'Pärnu']
Length: 3, dtype: str
Total revenue: 2065.79

store_location
Tallinn    9
Tartu      7
Pärnu      4
Name: count, dtype: int64

In [17]:
print("Unique customers:", df['customer_id'].nunique())
print("Locations:", df['store_location'].unique())
print("Total revenue:", df['total_price'].sum())
df['store_location'].value_counts()

Unique customers: 7
Locations: <StringArray>
['Tallinn', 'Tartu', 'Pärnu']
Length: 3, dtype: str
Total revenue: 2065.79

store_location
Tallinn    9
Tartu      7
Pärnu      4
Name: count, dtype: int64

In [18]:
print("Number of categories:", df['product_category'].nunique())
print("Categories:", df['product_category'].unique())
df['product_category'].value_counts()

Number of categories: 4
Categories: <StringArray>
['Dresses', 'Tops', 'Denim', 'Accessories']
Length: 4, dtype: str

product_category
Denim          6
Dresses        5
Tops           5
Accessories    4
Name: count, dtype: int64

In [19]:
df[df['store_location'] == 'Tallinn']

    customer_id   sale_date  total_price store_location product_category
0          1001  2024-01-15        89.99        Tallinn          Dresses
2          1003  2024-02-01       120.00        Tallinn            Denim
3          1001  2024-02-20        67.30        Tallinn      Accessories
6          1003  2024-03-15        33.50        Tallinn             Tops
7          1001  2024-04-10       145.00        Tallinn          Dresses
11         1003  2024-05-10        44.00        Tallinn             Tops
13         1001  2024-06-01       230.00        Tallinn          Dresses
17         1007  2024-07-01        65.00        Tallinn      Accessories
18         1003  2024-07-05        95.00        Tallinn          Dresses

In [20]:
df[(df['store_location'] == 'Tallinn') & (df['total_price'] > 100)]

    customer_id   sale_date  total_price store_location product_category
2          1003  2024-02-01        120.0        Tallinn            Denim
7          1001  2024-04-10        145.0        Tallinn          Dresses
13         1001  2024-06-01        230.0        Tallinn          Dresses

In [21]:
df.groupby('store_location')['total_price'].sum()

store_location
Pärnu      514.00
Tallinn    889.79
Tartu      662.00
Name: total_price, dtype: float64

In [22]:
customer_stats = df.groupby('customer_id')['total_price'].agg(['count', 'sum'])
customer_stats.sort_values('sum', ascending=False)

             count     sum
customer_id
1001             4  532.29
1004             3  477.00
1002             4  370.50
1003             4  292.50
1005             3  291.50
1007             1   65.00
1006             1   37.00

In [23]:
price = 150
print('Large' if price > 100 else 'Small')

price = 50
print('Large' if price > 100 else 'Small')

Large
Small

In [24]:
df['order_size'] = df['total_price'].apply(lambda x: 'Large' if x > 100 else 'Small')
df.head()

,customer_id,sale_date,total_price,store_location,product_category,order_size
0,1001,2024-01-15,89.99,Tallinn,Dresses,Small
1,1002,2024-01-16,45.50,Tartu,Tops,Small
2,1003,2024-02-01,120.00,Tallinn,Denim,Large
3,1001,2024-02-20,67.30,Tallinn,Accessories,Small
4,1002,2024-03-01,55.00,Tartu,Tops,Small

In [25]:
customer_summary = df.groupby('customer_id')['total_price'].agg(
    total_spend='sum',
    orders='count'
).reset_index()

customer_summary['vip_status'] = customer_summary['total_spend'].apply(
    lambda x: 'VIP' if x > 200 else 'Regular'
)

customer_summary.sort_values('total_spend', ascending=False)

   customer_id  total_spend  orders vip_status
0         1001       532.29       4        VIP
3         1004       477.00       3        VIP
1         1002       370.50       4        VIP
2         1003       292.50       4        VIP
4         1005       291.50       3        VIP
6         1007        65.00       1    Regular
5         1006        37.00       1    Regular

In [26]:
customers = pd.DataFrame({
    'customer_id': [1001, 1002, 1003, 1004, 1005, 1006, 1007],
    'first_name': ['Jüri', 'Kati', 'Maris', 'Peeter', 'Liina', 'Andres', 'Tiina']
})

merged = pd.merge(customer_summary, customers, on='customer_id', how='left')
merged.sort_values('total_spend', ascending=False)

   customer_id  total_spend  orders vip_status first_name
0         1001       532.29       4        VIP       Jüri
3         1004       477.00       3        VIP     Peeter
1         1002       370.50       4        VIP       Kati
2         1003       292.50       4        VIP      Maris
4         1005       291.50       3        VIP      Liina
6         1007        65.00       1    Regular      Tiina
5         1006        37.00       1    Regular     Andres